### ISSUE TITLE
Stopped working after update to latest image version

### ISSUE THREAD

**Issue by Totten98** [Fmstrat/samba-domain#44]
Hi I might need to help.
I updated the docker image to the latest version yesterday and everything stopped working, both shares and domain controller.
I'll paste the log, hope that someone can help me.

```
samba          | ==> /var/log/supervisor/ntpd-stdout---supervisor-c9hrx55p.log <==
samba          | 13 May 08:08:26 ntpd[13]: switching logging to file /var/log/ntp
samba          | 13 May 08:08:26 ntpd[13]: Listen and drop on 0 v6wildcard [::]:123
samba          | 13 May 08:08:26 ntpd[13]: Listen and drop on 1 v4wildcard 0.0.0.0:123
samba          | 13 May 08:08:26 ntpd[13]: Listen normally on 2 lo 127.0.0.1:123
samba          | 13 May 08:08:26 ntpd[13]: Listen normally on 3 eth0 172.18.0.3:123
samba          | 13 May 08:08:26 ntpd[13]: Listening on routing socket on fd #20 for interface updates
samba          | 13 May 08:08:26 ntpd[13]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
samba          | 13 May 08:08:26 ntpd[13]: kernel reports TIME_ERROR: 0x2041: Clock Unsynchronized
samba          |
samba          | ==> /var/log/supervisor/samba-stderr---supervisor-yfa9c7md.log <==
samba          | /usr/sbin/samba_dnsupdate: Traceback (most recent call last):
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/sbin/samba_dnsupdate", line 297, in check_dns_name
samba          | /usr/sbin/samba_dnsupdate:     ans = check_one_dns_name(normalised_name, d.type, d)
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/sbin/samba_dnsupdate", line 274, in check_one_dns_name
samba          | /usr/sbin/samba_dnsupdate:     return resolver.resolve(name, name_type)
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1176, in resolve
samba          | /usr/sbin/samba_dnsupdate:     timeout = self._compute_timeout(start, lifetime)
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/lib/python3/dist-packages/dns/resolver.py", line 997, in _compute_timeout
samba          | /usr/sbin/samba_dnsupdate:     raise Timeout(timeout=duration)
samba          | /usr/sbin/samba_dnsupdate: dns.exception.Timeout: The DNS operation timed out after 17.00490975379944 seconds
samba          | /usr/sbin/samba_dnsupdate:
samba          | /usr/sbin/samba_dnsupdate: During handling of the above exception, another exception occurred:
samba          | /usr/sbin/samba_dnsupdate:
samba          | /usr/sbin/samba_dnsupdate: Traceback (most recent call last):
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/sbin/samba_dnsupdate", line 842, in <module>
samba          | /usr/sbin/samba_dnsupdate:     elif not check_dns_name(d):
samba          | /usr/sbin/samba_dnsupdate:   File "/usr/sbin/samba_dnsupdate", line 299, in check_dns_name
samba          | /usr/sbin/samba_dnsupdate:     raise Exception("Timeout while waiting to contact a working DNS server while looking for %s as %s" % (d, normalised_name))
samba          | /usr/sbin/samba_dnsupdate: Exception: Timeout while waiting to contact a working DNS server while looking for A srv.mydomain.lan 172.18.0.3 as srv.mydomain.lan.
samba          | dnsupdate_nameupdate_done: Failed DNS update with exit code 1
```

I don't know where the problem came from and don't know how to fix it. I hope someone can help me.
Thanks, Totten98

**Comment by aczwink** [comment]
As far as I see this is definitely related to #43

**Comment by Totten98** [comment]
Solved by updating the samba configuration (smb.conf) with the new version one
